
### Создать аккаунт

POST http://localhost:8000/api/v1/signup HTTP/1.1
content-type: application/json

{
    "email": "test@test.com",
    "username": "test",
    "password": "test1234"
}

### Авторизоваться
POST http://localhost:8000/api/v1/login HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "test1234"
}

### Создать обзор
POST http://localhost:8000/api/v1/reviews HTTP/1.1
content-type: application/json

{
    "username": "test",
    "mbid": "test1234",
    "content": "Hello"
}


### Получить обзоры
GET http://localhost:8000/api/v1/reviews/test1234 HTTP/1.1